name: animal-sound-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - librosa
  - tqdm
  - ipywidgets
  - pip:
      - torch
      - torchvision
      - torchaudio
      - tensorflow
      - keras
      - audiomentations
      - pydub
      - openl3
      - hydra-core
      - wandb
