_wandb:
    value:
        cli_version: 0.21.0
        e:
            81iido0p2urqhxa1riecqx2o0xsaf6f0:
                codePath: Training.py
                codePathLocal: Training.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "928784576512"
                        used: "420094181376"
                email: harrypotter166at@gmail.com
                executable: C:\Users\linus\miniconda3\envs\animal-sound-ml\python.exe
                git:
                    commit: a49196bd4fbdeec91c69006de2963bb79978fe77
                    remote: https://github.com/Linus16666/Animal_Sound_Classification
                host: Envy-von-Linus
                memory:
                    total: "16441667584"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\linus\Animal_Sound_Classification\Training.py
                python: CPython 3.10.18
                root: C:\Users\linus\Animal_Sound_Classification
                startedAt: "2025-08-06T15:10:06.981355Z"
                writerId: 81iido0p2urqhxa1riecqx2o0xsaf6f0
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 16
                - 61
            "4": 3.10.18
            "5": 0.21.0
            "8":
                - 3
            "12": 0.21.0
            "13": windows-amd64
batch_size:
    value: 16
epochs:
    value: 150
learning_rate:
    value: 0.001
