"""
Convert inference_mic/crnn.tflite → inference_mic/esp32s3/model_data.h

Usage:
  python inference_mic/tools/gen_model_header.py

The output is a C header containing the TFLite flatbuffer as a
  static const uint8_t g_model_data[] PROGMEM / __attribute__((aligned(8))) ...
array that the ESP32-S3 firmware includes at compile time (stored in flash/DROM).
"""

import os
import struct

TFLITE_PATH = os.path.join(
    os.path.dirname(__file__), "..", "crnn.tflite"
)
OUT_PATH = os.path.join(
    os.path.dirname(__file__), "..", "esp32s3", "model_data.h"
)


def tflite_to_header(tflite_path: str, out_path: str) -> None:
    with open(os.path.normpath(tflite_path), "rb") as f:
        data = f.read()

    n = len(data)
    print(f"Model size: {n:,} bytes ({n/1024/1024:.2f} MB)")

    lines = [
        "/* Auto-generated by gen_model_header.py — do not edit. */",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"static const unsigned int g_model_data_len = {n}U;",
        "",
        "/* Stored in flash (DROM). 8-byte alignment required by TFLite. */",
        "static const uint8_t g_model_data[] __attribute__((aligned(8))) = {",
    ]

    # Emit 16 bytes per line
    for i in range(0, n, 16):
        chunk = data[i:i + 16]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"  {hex_vals},")

    lines.append("};")
    lines.append("")

    out_path = os.path.normpath(out_path)
    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    print(f"Written {out_path}")
    print("NOTE: This file is large (~6.5 MB). Compile with a partition scheme")
    print("      that has at least 9 MB for the app (e.g. a custom partition CSV).")


if __name__ == "__main__":
    tflite_to_header(TFLITE_PATH, OUT_PATH)
