"""
Generate mel_filterbank.h for ESP32-S3 firmware.

Produces a 64×1025 HTK-mel filterbank matching:
  torchaudio.transforms.MelSpectrogram(
      sample_rate=44100, n_mels=64,
      n_fft=2048, hop_length=512   # explicit in firmware
  )

Run this script once; copy the output header to inference_mic/esp32s3/.
"""

import numpy as np
import os

# Must match firmware / TFLite model tracing parameters
SAMPLE_RATE = 44100
N_FFT       = 2048
N_MELS      = 64
F_MIN       = 0.0
F_MAX       = SAMPLE_RATE / 2.0      # 22050 Hz
N_FREQS     = N_FFT // 2 + 1        # 1025


def hz_to_mel(f: float) -> float:
    """HTK mel scale."""
    return 2595.0 * np.log10(1.0 + f / 700.0)


def mel_to_hz(m: float) -> float:
    return 700.0 * (10.0 ** (m / 2595.0) - 1.0)


def build_filterbank(n_mels: int, n_freqs: int,
                     sample_rate: int, f_min: float, f_max: float
                     ) -> np.ndarray:
    """Return (n_mels, n_freqs) filterbank matching torchaudio melscale_fbanks."""
    mel_min = hz_to_mel(f_min)
    mel_max = hz_to_mel(f_max)

    # n_mels + 2 equally spaced mel points
    mel_points = np.linspace(mel_min, mel_max, n_mels + 2)
    hz_points  = mel_to_hz(mel_points)

    # Map to FFT bin indices (float)
    bin_points = hz_points / (sample_rate / 2.0) * (n_freqs - 1)

    fb = np.zeros((n_mels, n_freqs), dtype=np.float32)
    for m in range(n_mels):
        lo  = bin_points[m]
        ctr = bin_points[m + 1]
        hi  = bin_points[m + 2]
        for k in range(n_freqs):
            if lo <= k <= ctr:
                fb[m, k] = (k - lo) / (ctr - lo) if ctr != lo else 0.0
            elif ctr < k <= hi:
                fb[m, k] = (hi - k) / (hi - ctr) if hi != ctr else 0.0

    # Normalise each filter by its bandwidth (torchaudio norm=None → no normalisation)
    return fb


def write_header(fb: np.ndarray, out_path: str) -> None:
    n_mels, n_freqs = fb.shape
    lines = [
        "/* Auto-generated by gen_mel_filterbank.py — do not edit. */",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"static const int   MEL_N_MELS  = {n_mels};",
        f"static const int   MEL_N_FREQS = {n_freqs};",
        "",
        f"static const float MEL_FILTERBANK[{n_mels}][{n_freqs}] = {{",
    ]
    for m in range(n_mels):
        row_vals = ", ".join(f"{v:.8e}f" for v in fb[m])
        lines.append(f"    {{ {row_vals} }},")
    lines.append("};")
    lines.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    print(f"Written {out_path}  ({n_mels}×{n_freqs})")


if __name__ == "__main__":
    fb = build_filterbank(N_MELS, N_FREQS, SAMPLE_RATE, F_MIN, F_MAX)
    out = os.path.join(os.path.dirname(__file__), "..", "esp32s3", "mel_filterbank.h")
    out = os.path.normpath(out)
    write_header(fb, out)
